21-rails-auth/bookapp/config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :books

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

21-rails-auth/bookapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

21-rails-auth/bookapp/app/models/author.rb
class Author < ApplicationRecord
  has_secure_password
  
  has_many :books
end

21-rails-auth/bookapp/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

21-rails-auth/bookapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_author

  def current_author
    if session[:author_id] && !session[:author_id].nil?
      @author = Author.find_by(id: session[:author_id])
    else
    end
  end

  def logged_in?
    !!current_author
  end

  def authorized
    if logged_in?
      current_author
    else
      redirect_to login_path
    end
  end

end

21-rails-auth/bookapp/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_action :current_author, only: [:show, :edit, :update, :destroy]
  before_action :authorized

  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.valid?
      @author.save
      redirect_to authors_path
    else
      flash[:error] = "This didn't work fam.. Try again!!"
      redirect_to new_author_path
    end
  end

  def show
  end

  def edit
  end

  def update
    @author.update(author_params)
    redirect_to author_path(@author)
  end

  def destroy
    @author.destroy
  end

  private
  def author_params
    params.require(:author).permit(:title, :desc, :author_id)
  end

end

21-rails-auth/bookapp/app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :find_book, only: [:show, :edit, :update, :destroy]
  before_action :authorized

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.author = current_author

    if @book.valid?
      @book.save
      redirect_to books_path
    else
      flash[:error] = "This didn't work fam.. Try again!!"
      redirect_to new_book_path
    end
  end

  def show
  end

  def edit
  end

  def update
    @book.update(book_params)
    redirect_to book_path(@book)
  end

  def destroy
    @book.destroy
  end

  private
  def find_book
    @book = Book.find_by(id: params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :desc)
  end

end

21-rails-auth/bookapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @author = Author.find_by(:username => sessions_params[:username])
    if @author && @author.authenticate(sessions_params[:password])
      session['author_id'] = @author.id
      redirect_to author_path(@author)
    else
      redirect_to login_path
    end
  end

  def destroy
    session['author_id'] = nil
    redirect_to login_path
  end

  private
  def sessions_params
    params.permit(:username,:password)
  end

end

21-rails-auth/bookapp/app/helpers/application_helper.rb
module ApplicationHelper
end

21-rails-auth/bookapp/app/helpers/authors_helper.rb
module AuthorsHelper
end

21-rails-auth/bookapp/app/helpers/books_helper.rb
module BooksHelper
end

21-rails-auth/bookapp/app/views/books/edit.html.erb
<h1>Edit a book</h1>

<%= form_for @book, method: :patch do |f| %>
    Title:
      <%= f.text_field :title %> <br /><br />
    Description:
      <%= f.text_field :desc %> <br /><br />

    <%= f.submit %>
<% end %>

21-rails-auth/bookapp/app/views/books/index.html.erb
<h1>List of all books</h1>

<% @books.each do |book| %>
  <ul>
    <li> <b> Title: <%= book.title %> </b> </li>
    <li> Description: <%= book.desc %> </li>

    <% if book.author_id == current_author.id %>
      <%= link_to "Edit", edit_book_path(book) %>
      <%= button_to "Delete", book, :method => :delete %>
    <% end %>
  </ul>
<% end%>

21-rails-auth/bookapp/app/views/books/new.html.erb
<h1>Create a new book</h1>

<% if flash[:error]%>
  <h3 style='color: red;'>
    Error: <%= @book.errors.full_messages %>
  </h3>
<% end %>


<%= form_for @book, method: :post do |f| %>
    Title:
      <%= f.text_field :title %> <br /><br />
    Description:
      <%= f.text_field :desc %> <br /><br />
  
    <%= f.submit %>
<% end %>

21-rails-auth/bookapp/app/views/books/show.html.erb
<h1>Authored by: <%= @book.author.username %> </h1>

<p>
  <b>Title:</b> <%= @book.title %> <br />
  <b>Description:</b> <%= @book.desc %>
</p>

21-rails-auth/bookapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>