17-rails-forms-associations/doctoroffice/config/routes.rb
Rails.application.routes.draw do
  resources :doctors 
  resources :patients, only: [:index, :show, :new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

17-rails-forms-associations/doctoroffice/app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :patients
end

17-rails-forms-associations/doctoroffice/app/models/patient.rb
class Patient < ApplicationRecord
    belongs_to :doctor
end

17-rails-forms-associations/doctoroffice/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

    def index
        @doctors = Doctor.all

        @images  = ["1-doctor.jpg", "2-doctor.jpg", "3-doctor.jpg", "4-doctor.jpg", "5-doctor.jpg"]
        @random_no = rand(1...5)
        @random_image = @images[@random_no]
    end

    def show
        @doctor = Doctor.find(params[:id])
        
    end

    def new
        @doctor = Doctor.new 
    end

    def create
        @doctor = Doctor.create(name: params[:doctor][:name], specialty: params[:doctor][:specialty])
        redirect_to '/doctors'
    end

    def edit
        @doctor = Doctor.find(params[:id])
    end

    def update
        @doctor = Doctor.find(params[:id])
        @doctor.update(name: params[:doctor][:name], specialty: params[:doctor][:specialty])
        redirect_to doctors_path(@doctor)
    end

    def destroy
        @doctor = Doctor.find(params[:id])
        @doctor.destroy
        redirect_to doctors_path(@doctor)
    end

    private 

    def doctor_params 
        params.require(:doctor).permit(:name)
    end
end

17-rails-forms-associations/doctoroffice/app/controllers/patients_controller.rb
class PatientsController < ApplicationController

    def index
        @patients = Patient.all
    end

    def show
        @patient = Patient.find(params[:id])
    end

    def new
        @patient = Patient.new
    end

    def create
        @patient = Patient.new
        @patient.name = params[:patient][:name]
        @patient.condition = params[:patient][:condition]
        @patient.doctor_id = params[:patient][:doctor_id]
        @patient.save

        redirect_to patient_path(@patient)
    end
end

17-rails-forms-associations/doctoroffice/app/helpers/doctors_helper.rb
module DoctorsHelper
end

17-rails-forms-associations/doctoroffice/app/views/doctors/edit.html.erb
<div class="container" style="padding-top: 30px;">
        <h1 class="display-3" style="padding-top: 30px;">Edit Doctors Form</h1>
        <br/>
        <p>Made a boo-boo? Change your file using this form. </p>
    </div>
    
    <div class="container" style="padding-top: 30px;">
        <%= form_for @doctor do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
    
        <%= f.label :specialty %>
        <%= f.text_field :specialty %>
    
        <%= f.submit %>
        <% end %>

        <%= button_to "Delete", doctor_path(@doctor), method: :delete %>

    </div>

17-rails-forms-associations/doctoroffice/app/views/doctors/index.html.erb
<h1 class="display-3" style="padding-top: 30px;">Our Family of Doctors</h1>

<div class="container">
    <div class="row row-cols-2">

        <div class="col">
            <h2 style="padding: 15px;">Featured Doctor: Doctor Who</h2>
            <div style="padding: 20px;"><%= image_tag (@random_image) %></div>
            <p>A time-traveling immortal hailing from Gallifrey, Doctor Who specializes in otherworldly illnesses and saving the day. He's currently accepting patients and looks forward to becoming your new best friend. </p>
        </div>

        <div class="col"> 
            <ul style= "list-style-type: none;">
                <% @doctors.each do |doctor| %>
                <li style="padding-top: 20px;"><h6><%= link_to doctor.name, doctor %>, <%= doctor.specialty %></h6></li>
                <% end %>
            </ul>
        </div>

    </div>
</div>

<div class="container" style="padding-top: 30px;">
    <h3>Newly regenerated? Add yourself to the family <%= link_to "here.", "/doctors/new" %></h3>
</div>

17-rails-forms-associations/doctoroffice/app/views/doctors/new.html.erb
<div class="container" style="padding-top: 30px;">
    <h1 class="display-3" style="padding-top: 30px;">New Doctors Form</h1>
    <br/>
    <p>Are you new to our family of practitioners? Add yourself to our database using this form. </p>
</div>

<div class="container" style="padding-top: 30px;">
    <%= form_for @doctor do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>


    <%= f.label :specialty %>
    <%= f.text_field :specialty %>

    <%= f.submit %>
    <% end %>
</div>

17-rails-forms-associations/doctoroffice/app/views/doctors/show.html.erb
<div class="container">
    <h1 class="display-3" style="padding-top: 30px;"><%= @doctor.name %></h1>
    <br/>
</div>

<div class="container">
    <h1 class="display-6"><%= @doctor.specialty %></h1>
    <br>
    <p>Dolores quis quia ad quo voluptates. Maxime delectus totam numquam. Necessitatibus vel atque qui dolore. Id neque nemo. Dolores iusto facere est ad. Accusamus ipsa dolor ut. Et officiis ut hic. Sunt asperiores minus distinctio debitis ipsa dolor. Minima eos deleniti.</p>
</div>

<div class="container" style="padding-top: 50px;">
    <p>Not your flavor? Learn about another doctor, <%= link_to "here.", "/doctors" %></p>
    <p>To edit your file, click <%= link_to "here.", edit_doctor_path(@doctor) %></p>
</div>